### ISSUE TITLE
Stored xss

### ISSUE THREAD

**Issue by zftishack** [iteachyou-wjn/dreamer_cms#10]
Hello, I'm a penetration test engineer-mb
Affected version: 3.0.1
There is no xxs filter in the lower version
<img width="1192" alt="1" src="https://user-images.githubusercontent.com/58795040/224049756-2975ffcf-4f44-43cd-bafe-8936d8f7715c.png">
 At the same time, there is a low-version editor, where there is a stored xss 
<img width="1263" alt="2" src="https://user-images.githubusercontent.com/58795040/224049914-5de786dd-6465-498b-80b4-406f9b5d9f92.png">
<img width="1269" alt="3" src="https://user-images.githubusercontent.com/58795040/224049953-d76aa041-ae18-4348-a09f-818a6849733d.png">

**Comment by iteachyou-wjn** [comment]
completed
