### ISSUE TITLE
Arbitrary file upload vulnerability

### ISSUE THREAD

**Issue by XinCaoZ** [iteachyou-wjn/dreamer_cms#11]
Hello, I'm a penetration test engineer
I found that the upload function point of the interface did not verify the suffix or content of the uploaded file, resulting in the arbitrary upload of maliciously constructed content for xss hijacking.
![image](https://user-images.githubusercontent.com/64942080/226236492-78cd3292-c0ca-4dc4-9a92-27a50192f0cf.png)

![image](https://user-images.githubusercontent.com/64942080/226236316-10679d10-a538-4bcd-843b-e69dca889f28.png)

**Comment by iteachyou-wjn** [comment]
completed
