### ISSUE TITLE
配置不当引起sql注入漏洞

### ISSUE THREAD

**Issue by zaizainani** [iteachyou-wjn/dreamer_cms#13]
[sqlattack-en.pdf](https://github.com/iteachyou-wjn/dreamer_cms/files/12511354/sqlattack-en.pdf)
      尊敬的dreamer cms作者，你好，我这边在对dreamer cms进行代码审计时发现了一处sql注入漏洞。当应用系统mybatis配置允许多行查询即allowMultiQueries=true时，dreamer cms存在sql注入漏洞可以执行任意sql语句。
      漏洞代码位置是在FormMapper.xml中id="alterTableAddColumn”,id="alterTableDropColumn”,id="alterTableChangeColumn"，另外FieldServiceImpl.java中alterTableChangeColumn，alterTableAddColumn等方法调用时，也没有对传入的数据进行校验，导致了sql注入。具体可参考我上传的文件，谢谢。

**Comment by iteachyou-wjn** [comment]
系统默认不支持多行执行
