### ISSUE TITLE
a CSRF vulnerability at the location of component /admin/u/toIndex.

### ISSUE THREAD

**Issue by CP1379767017** [iteachyou-wjn/dreamer_cms#15]
detail:
[https://github.com/CP1379767017/cms/blob/dreamcms_vul/CSRF exists at the location where delete a user location.md](https://github.com/CP1379767017/cms/blob/dreamcms_vul/CSRF%20exists%20at%20the%20location%20where%20delete%20a%20user%20location.md)

**Comment by iteachyou-wjn** [comment]
resolved
