### ISSUE TITLE
Arbitrary file upload vulnerability in Style Setting

### ISSUE THREAD

**Issue by xcx1r3** [iteachyou-wjn/dreamer_cms#18]
In the backend, user can upload zip files through the style settings module.
![image](https://github.com/user-attachments/assets/81d87c89-3119-41e8-b333-fdd48a9d062f)
Although the `..\` and `../` is filtered, we can create a zip file containing  `..*..*..*flag`, as the following code will replace it for us:
![image](https://github.com/user-attachments/assets/339b1ba6-71bd-4d4b-86cf-fb7af65876f4)
This is how the zipfile look like:
![image](https://github.com/user-attachments/assets/4943e516-ae9f-4cca-9b2b-0dbb5201611e)
After uploading the zip file, we can find our flag in the web root:
![image](https://github.com/user-attachments/assets/98fb3a17-63b0-44e1-85a9-99cc1f229bad)
If the running system is Linux and the CMS is initiated by root user, an attacker could upload a cron file to execute commands on the target system. (For example, you can attach a file named `..*..*..*..*..*..*..*etc*crontab` in zip to overwrite the cron file.)
Alternatively, they could overwrite the /root/.ssh/authorized_keys or /etc/passwd files to connect to the server or escalate their privileges.

**Comment by iteachyou-wjn** [comment]
The theme file name and file names in the compressed file have been filtered.
