### ISSUE TITLE
Arbitrary file read vulnerability

### ISSUE THREAD

**Issue by ljk5** [iteachyou-wjn/dreamer_cms#7]
This vulnerability is present in the current version

Copy the default style file in cms, and add theme.json and recompress it into a zip file
![665f8184c4b41b4c53303fcb1da4616](https://user-images.githubusercontent.com/110451039/205639941-d82e48bb-857c-4208-a053-2bc0dd071350.png)
Where theme.json is as follows
![b0292e16_8882137](https://user-images.githubusercontent.com/110451039/205639975-1da3250f-0631-4e50-b389-763ca89a53f5.png)
Upload and use this theme
![4d74ae23_8882137](https://user-images.githubusercontent.com/110451039/205640008-676bab57-4ad4-416a-aa0e-9357cc97984d.png)
![f7faca86_8882137](https://user-images.githubusercontent.com/110451039/205640043-cce47600-aef6-46ef-bc60-e78359e1488a.png)

Enter the template management to see the files in the root directory

**Comment by ljk5** [comment]
{"themeName":"asdasd", "themeImage": "asdasdas", "themeAuthor":"asdasd", "themePath":"../../../../../../../../../../../../../../../"}

**Comment by iteachyou-wjn** [comment]
themePath should folder name. eq:123
