### ISSUE TITLE
Dreamer CMS overreach loophole

### ISSUE THREAD

**Issue by ljk5** [iteachyou-wjn/dreamer_cms#9]
Hello, I'm Li Jiakun, a security researcher
Affected version: 4.0.0
Any user can access the port without verifying the current user information
![image](https://user-images.githubusercontent.com/110451039/223903255-a87c4cdc-b567-48b8-9211-095d3823d735.png)
Background applications do not control permissions, or only control permissions on menus and buttons. As a result, malicious users can access or control data or pages owned by other roles by guessing the urls or sensitive parameter information of other management pages, achieving the purpose of enhancing permissions.

**Comment by iteachyou-wjn** [comment]
completed
